CC = g++
CFLAGS = -std=c++11 -Wall
TARGET = coursework1-1
SRCS = main.cpp
OBJS = $(SRCS:.cpp=.o)

EXECUTABLE = coursework1-1

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(TARGET)

%.o: %.cpp
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)